//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudioExpress_BLL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class EstudioExpress : global::System.Configuration.ApplicationSettingsBase {
        
        private static EstudioExpress defaultInstance = ((EstudioExpress)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EstudioExpress())));
        
        public static EstudioExpress Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StringDeConexion {
            get {
                return ((string)(this["StringDeConexion"]));
            }
            set {
                this["StringDeConexion"] = value;
            }
        }
    }
}
